[package]
name = "whispers-below"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib", "rlib"]
